### ISSUE TITLE
Inconsistent transitions from winner to loser bracket

### ISSUE THREAD

**Issue by alfiehub** [teijo/jquery-bracket#122]
Ive noticed that where in the loser bracket the losing team will be placed is somewhat inconsistent.

![image](https://user-images.githubusercontent.com/6656328/30250362-480a7944-964d-11e7-8eb8-476bac4cb89d.png)

As you can see, `Team 5` is sent to the `1st match` of the `4th loser bracket round` from the `1st match` in the `3rd winner bracket round`.
But `Team 13`, the loser of the `4th match` in the `2nd winner bracket round` is sent to the `1st match` of the `2nd loser bracket round`.

So why isnt `Team 5` sent to the `2nd match` of the `4th loser bracket round`?
Or is this the expected behavior?

**Comment by teijo** [comment]
If I understood your question right, then yes, it's the expected behaviour.

The seeding for matches assigned from winners' bracket to losers' bracket get reversed every second round. The reason being that if losers got assigned to same branch of the losers' bracket, they would have a rematch immediately. By alternating the seeding for losing teams, the time a losing team might encounter the team that dropped them to losers' bracket is maximized.

Example: `Team 8` wins `Team 7` in first round, `Team 8` loses to `Team 5` next. Now, if `Team 7` won `Team 6` in the first round of loser bracket, it would immediately face `Team 8` unless `Team 8` got seeded in reverse order as it is now.

**Comment by alfiehub** [comment]
Ah, I understand. Great answer! 

Thank you 😃
