### ISSUE TITLE
Error on double elimination bracket with TBD and BYE

### ISSUE THREAD

**Issue by papangproduction** [teijo/jquery-bracket#126]
Hi,
I've an potential issue on the double elimination bracket with TBD on source as can see on the image below (image generated from documentation website http://www.aropupu.fi/bracket).

In my opinion, texts highlighted in yellow should display TBD and not BYE. Am i wrong ?

![image](https://user-images.githubusercontent.com/18103063/31163790-25b7e0c4-a8f5-11e7-9718-7b19852bd22e.png)

**Comment by kpagcha** [comment]
I have the exact same issue, and I was going to post about it literally now. Glad someone else is on this as well!

**Comment by teijo** [comment]
Yup, looks like a bug, good spotting! 🙂

**Comment by kpagcha** [comment]
Is there a quickfix for it though?

**Comment by teijo** [comment]
Well it probably needs a proper fix. Can't remember how the upcoming matches are propagated in the code, might be trivial, might need moderate amount of work.

**Comment by kpagcha** [comment]
I think a way to solve it would be to establish that if the source match is a BYE vs TBD then the proper selection would be TBD.

I would test this myself but sadly I am unfamiliar with the code and it is undocumented. If you can think where this behavior is defined I can try it and see how it works.

**Comment by kpagcha** [comment]
I did patch this through tricks and tweaks but it's an ugly workaround. Is there any new development on this? Or at least point out how I could work it out myself? (what part of the plugin code should I look at)

**Comment by teijo** [comment]
I spent some time on this but didn't manage to fix it.

The problem is that the `BranchType.BYE/.TBD` is determined by only from the "first" team of the match it comes from via `.source()`: https://github.com/teijo/jquery-bracket/blob/master/src/jquery.bracket.ts#L147 set e.g. here: https://github.com/teijo/jquery-bracket/blob/master/src/jquery.bracket.ts#L695

First approach was to just pass both "sources" for this purpose, but turned out that there's some illogical way the end of the branch is determined, probably here: https://github.com/teijo/jquery-bracket/blob/master/src/jquery.bracket.ts#L384, causing `emptyBranch()` to not really work.

Anyway, will need more investigation...

**Comment by teijo** [comment]
Commit 3ed60f9566b27ad06bb0c27cf255e6f11ec80f9f fixes `TBD` propagation in single elimination brackets. Double elimination does not yet work correctly.

**Comment by teijo** [comment]
Fix now in master, will be part of next release unless it broke in some other way. 🙂
