### ISSUE TITLE
Always show teams in ascending order of seed values

### ISSUE THREAD

**Issue by sheharyarn** [teijo/jquery-bracket#29]
How can I always show participating teams in Ascending Order of their `seed`? For example, my `init` data is:

```javascript
init: {
	teams: [
		[{name: "aaaaaa"}, {name: "bbbbbb"}],
		[{name: "cccccc"}, {name: "dddddd"}]
	],
	results: [[[[]]],[],[]]
}

```

But sometimes they're are in reverse order in `loserBracket` and `finalBracket`:

![screen shot 2015-01-12 at 8 09 08 pm](https://cloud.githubusercontent.com/assets/2355108/5705093/735b3d80-9a98-11e4-9a47-172d60ed902f.png)

Is it possible for me to display the matches between `[dddddd, aaaaa]` & `[cccccc, aaaaaa]` as `[aaaaaa, dddddd]` & `[aaaaaa, cccccc]`?

**Comment by teijo** [comment]
Hi,

It's not possible to affect the flow. In some cases, like `[cccccc, aaaaaa]` it wouldn't be a problem from seeding point of view swapping them around, but it would require additional logic. Final cannot really be swapped as the connectors would cross and they wouldn't be visually clear.

When it comes to any bracket bigger than your example, the bracket purposefully reverses the matches of every second loser bracket round in order to postpone rematches as far into the end of the tournament as possible. For example: team A and B play in WB round 1, B loses, A loses its next WB round against C, reversing the seeding order in LB here prevents the otherwise immediate A - B rematch.

**Comment by sheharyarn** [comment]
Yeah, that makes sense. Anyways, this was conflicting with my custom result calculation in the backend (as mentioned in #17), I found a workaround. I'm also storing the order of the seeds when saving a match. [See this]().
