### ISSUE TITLE
Link Brackets

### ISSUE THREAD

**Issue by dnavarrojr** [teijo/jquery-bracket#55]
Is there a way to link two or more brackets together?

For example, I have a LR bracket and RL bracket and I need to link them together so the winner from the LR bracket plays the winner of the RL bracket.

**Comment by dnavarrojr** [comment]
Or possibly putting both sides in the same bracket.

`.bracket({ 
  init: [leftBracket, 'lr'],
  init: [rightBracket, 'rl']
})`

**Comment by teijo** [comment]
There isn't such functionality.

If I understand what you really want to achieve, it would be a matter of layout instead of merging two different brackets together, something like this:

![Split bracket](https://image.slidesharecdn.com/64teambracketsingleelimination-151126005325-lva1-app6891/95/64-team-bracket-single-elimination-1-638.jpg)

In that case, it should just be a new configuration option, e.g. `layout: 'split'`.

**Comment by teijo** [comment]
You can create a new issue as a feature request if this is what you'd like to have, thanks.
