### ISSUE TITLE
Working with BYEs

### ISSUE THREAD

**Issue by rainiur** [teijo/jquery-bracket#70]
By leaving one of the teams in a match blank it leaves a "--" for the name. I would like to create this into a BYE and let the other player automatically advance to the next round. How would I go about doing this outside of assigning a team named BYE?

**Comment by teijo** [comment]
There isn't any built-in way of doing this so far, and even the name "BYE" is just a convention. 

This feature is related to #8.

**Comment by teijo** [comment]
Adding this just as a note to self, or anyone interested:

A team forfeiting a match or tournament is a separate problem from not being in the tournament to begin with (i.e. what #8 is about). The question is, if a forfeit should be indicated in some way instead of giving e.g. 1-0 score for the team that got default win. Also, if a team advances in a double elimination, and then forfeits the whole tournament, instead of giving BYE in the possible winner bracket, the team would need to BYE automatically also in loser bracket.

**Comment by teijo** [comment]
@rainiur BYE support is now implemented and available in the version 0.8.0.

**Comment by teijo** [comment]
Created a new issue, #78 for teams dropping from tournaments.
