### ISSUE TITLE
Disabling Team's Names

### ISSUE THREAD

**Issue by g0nP** [teijo/jquery-bracket#72]
Is there a way to prevent the user from editing the Team's name? I'm loading data from DB and I want to allow the user to change just the scores.

**Comment by teijo** [comment]
Hi,

There's no built-in way of disabling only the edit, but you might be able to do a hack by using decorators and calling the `doneCb` immediately from the `edit` callback. See for details: http://www.aropupu.fi/bracket/#customHandlers

No built-in way of changing the size.

P.S. Please create two issues rather than merging them into one, then it will be possible to solve each separately, thanks!

**Comment by teijo** [comment]
> I'm loading data from DB and I want to allow the user to change just the scores.

So how should it actually work in your case, should all scores be editable?

**Comment by g0nP** [comment]
Hi teijo! Sorry for the "double issue". I have created a new one for the box width and edited here.

As you said, all the scores should be editable. When the page loads, I retrieve the scores from DB if they exists. The user is able to input new scores or edit previous ones in case of error.

**Comment by teijo** [comment]
Implemented in 1a5d5ede2b550b894076c90b99f7297fff2ecda0. Comes to next release.

You can give `disableTeamEdit: boolean`. Setting it to true will require you to also set `disableResize` to `true`, otherwise you could remove teams, therefore "editing" them.
