### ISSUE TITLE
After Data customization labels and score become non editable

### ISSUE THREAD

**Issue by amalk1** [teijo/jquery-bracket#81]
After Data customization if we add new players using the + button the label and score are non editable, looks like an issue..?

**Comment by teijo** [comment]
Are you getting the same problem as the demo? http://localhost:8000/index.html#customHandlers

Expand tournament from `+` and then try to edit: `Uncaught TypeError: Cannot read property 'name' of null`

**Comment by teijo** [comment]
Fixed the demo.

Do you have another use case where an error occurs? If not, I'll close this issue.

**Comment by amalk1** [comment]
This was the same issue I was referring to. In the demo now I can edit label, but after edit it goes off..
but I understood the problem. 
I have a question, in case of  customization how can I achieve the new BYE functionality as it is ..?

**Comment by teijo** [comment]
Seems I gave my dev address, fixed it to my earlier post :)

The BYE should work the same as without customization, i.e. teams playing against BYE get a default win and advance.

**Comment by amalk1** [comment]
Thanks Teijo. In the customization demo on clicking the + button if I have to display the BYE nodes (currently it displays blank nodes) how can I achieve this? or how can I skip customization only for bye nodes and use default label. Also how to see the TBD label automatically appearing for other nodes?

**Comment by teijo** [comment]
Yup, can see that.

At the moment the `null` team object is replaced with a string `BYE` or `TBD` that is passed to the `render` decorator callback. This is of course not good in case the bracket uses plain text for the teams and a team decides to be called `BYE` or `TBD`. There wouldn't be any way to identify how to render it.

This should definitely be fixed in the `render` decorator API, i.e. the type of the block would be passed as a new argument.

This is where the problem occurs from curomization point of view: https://github.com/teijo/jquery-bracket/blob/master/src/jquery.bracket.ts#L797

If the name conflict isn't a problem, you can just check if the callback gets a string `BYE` or `TBD` and decide how to do the rendering based on that.

**Comment by teijo** [comment]
First implementation in master https://github.com/teijo/jquery-bracket/commit/21c41b748193cdc488b16c16e04e2ed9480a0634#diff-c75eed3142d70683082eaa91643195e5R347

**Comment by amalk1** [comment]
Thank you so much Teijo!!
