### ISSUE TITLE
Double-elimination: position of the Winner Bracket losers in the Losing Bracket

### ISSUE THREAD

**Issue by kpagcha** [teijo/jquery-bracket#92]
Edit: first of all, how do you even create a double-elimination bracket with an empty LB? The guide says it should have this shape: `[[[[]]], [], []]` but I can't get it right. I just want to see the positions where the losers are dragged to for brackets higher than the example in the guide.

I am trying to understand the logic behind the chosen order when dragging losers to the losing bracket, because every single example I see (this plugin and other instances like [this one](https://en.wikipedia.org/wiki/Double-elimination_tournament#/media/File:NSB-doubleelim-draw-2004.png) or [this one](http://challonge.com/sommerchicago)).

So the [example ](http://www.aropupu.fi/bracket/#big)in the demo site does the following for major stages (I am talking only about major stages because minor stages seem to be consistent in every example, it's simply an "advance round" move):

For each match `i` in the Quarterfinals (Winner Bracket), the losing team ends up in the match `n-i` (being `n` the number of matches in Loser Bracket QF). However, in the WB Semifinals, the `i` loser ends up in the `i` match of the LB Semifinals.

The example in wikipedia does the same for the SF, however, for the QF, the losers in the bottom half go to the top half of LB QF and the losers in the top half go to the bottom.

Finally, in the last example, the order of the SF is reversed (loser `i` goes to the opposite match), and in the rest of the rounds does the opposite than the example from wikipedia: losers from the top half go to the top and bottom to bottom, except the order is reversed: match 1 loser goes to match 2 in the LB, match 2 loser goes to match 1 in the LB, etc...

So what's the "correct" way to do it? What is this plugin's choice based on? Any insight on the algorithms the other examples are using and why?

**Comment by teijo** [comment]
> The guide says it should have this shape: [[[[]]], [], []] but I can't get it right.

You mean you don't get it to work?

This works just fine for me: `{teams: [['a', 'b'], ['c', 'd']], results: [[[[]]], [], []]}`. Creates an uninitialized double elimination bracket with four teams assigned into the first round of winner bracket.

If you read the "Data structure" documentation (beginning of http://www.aropupu.fi/bracket) you can see how the arrays represent the brackets, i.e. the bracket expects to see three inner brackets to indicate double elimination as each array contains results for a specific sub-bracket (winner, loser, or final).

> I just want to see the positions where the losers are dragged to for brackets higher than the example in the guide.

The bracket doesn't visualize the advancement at the moment. If that's what you're looking for, please create a feature request.

> So what's the "correct" way to do it? What is this plugin's choice based on? Any insight on the algorithms the other examples are using and why?

I don't know if there is any "correct" way of doing it. In the library implementation, every second round in loser bracket the teams are seeded in reverse order in order to maximize the time it takes for two teams to meet again. Consider this: A and B play in winner bracket, B loses, A loses next WB match, A and B should not play against each other immediately (assuming B won the following LB match after dropping there).

Reversing the order assigns teams into different branch in loser bracket, meaning that they'll meet much later in the tournament when the branches merge.

The implementation is here: https://github.com/teijo/jquery-bracket/blob/d3b8ca8ee20d036d547b51679c9d2e7dfd358639/src/jquery.bracket.ts#L465

**Comment by kpagcha** [comment]
I am going to close this one, I figured it out. I was just missing one extra depth to let the plugin know it is a double-elimination bracket.
